specfile_path: distribution-gpg-keys.spec

files_to_sync:
  # Copy a file from root of the upstream repo to dist-git.
  - distribution-gpg-keys.spec
  # If you copy packit.yaml downstream, you can then take advantage of
  # `sync-from-downstream` command.
  - .packit.yaml

upstream_package_name: distribution-gpg-keys

downstream_package_name: distribution-gpg-keys


srpm_build_deps:
  - tito
  - git

#create_tarball_command: tito build --test --tgz -o ./

jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
      - fedora-rawhide-x86_64
